#############################################################################
# Makefile for building: myclient
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 1 09:43:06 2017
# Project:  myclient.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile myclient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		clinetmainwindow.cpp \
		clientsocket.cpp \
		logindialog.cpp \
		registerdialog.cpp \
		networkconfigdialog.cpp \
		qcustomplot.cpp \
		picenv.cpp \
		playbk.cpp moc_clinetmainwindow.cpp \
		moc_clientsocket.cpp \
		moc_logindialog.cpp \
		moc_registerdialog.cpp \
		moc_networkconfigdialog.cpp \
		moc_qcustomplot.cpp \
		moc_picenv.cpp \
		moc_playbk.cpp
OBJECTS       = main.o \
		clinetmainwindow.o \
		clientsocket.o \
		logindialog.o \
		registerdialog.o \
		networkconfigdialog.o \
		qcustomplot.o \
		picenv.o \
		playbk.o \
		moc_clinetmainwindow.o \
		moc_clientsocket.o \
		moc_logindialog.o \
		moc_registerdialog.o \
		moc_networkconfigdialog.o \
		moc_qcustomplot.o \
		moc_picenv.o \
		moc_playbk.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		myclient.pro
QMAKE_TARGET  = myclient
DESTDIR       = 
TARGET        = myclient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_clinetmainwindow.h ui_logindialog.h ui_registerdialog.h ui_networkconfigdialog.h ui_picenv.h ui_playbk.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myclient.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile myclient.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile myclient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/myclient1.0.0 || $(MKDIR) .tmp/myclient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/myclient1.0.0/ && $(COPY_FILE) --parents clinetmainwindow.h clientsocket.h logindialog.h registerdialog.h networkconfigdialog.h CommandType.h qcustomplot.h picenv.h playbk.h .tmp/myclient1.0.0/ && $(COPY_FILE) --parents main.cpp clinetmainwindow.cpp clientsocket.cpp logindialog.cpp registerdialog.cpp networkconfigdialog.cpp qcustomplot.cpp picenv.cpp playbk.cpp .tmp/myclient1.0.0/ && $(COPY_FILE) --parents clinetmainwindow.ui logindialog.ui registerdialog.ui networkconfigdialog.ui picenv.ui playbk.ui .tmp/myclient1.0.0/ && (cd `dirname .tmp/myclient1.0.0` && $(TAR) myclient1.0.0.tar myclient1.0.0 && $(COMPRESS) myclient1.0.0.tar) && $(MOVE) `dirname .tmp/myclient1.0.0`/myclient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/myclient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_clinetmainwindow.cpp moc_clientsocket.cpp moc_logindialog.cpp moc_registerdialog.cpp moc_networkconfigdialog.cpp moc_qcustomplot.cpp moc_picenv.cpp moc_playbk.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clinetmainwindow.cpp moc_clientsocket.cpp moc_logindialog.cpp moc_registerdialog.cpp moc_networkconfigdialog.cpp moc_qcustomplot.cpp moc_picenv.cpp moc_playbk.cpp
moc_clinetmainwindow.cpp: picenv.h \
		qcustomplot.h \
		playbk.h \
		clinetmainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clinetmainwindow.h -o moc_clinetmainwindow.cpp

moc_clientsocket.cpp: clientsocket.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clientsocket.h -o moc_clientsocket.cpp

moc_logindialog.cpp: logindialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) logindialog.h -o moc_logindialog.cpp

moc_registerdialog.cpp: registerdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) registerdialog.h -o moc_registerdialog.cpp

moc_networkconfigdialog.cpp: networkconfigdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) networkconfigdialog.h -o moc_networkconfigdialog.cpp

moc_qcustomplot.cpp: qcustomplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qcustomplot.h -o moc_qcustomplot.cpp

moc_picenv.cpp: qcustomplot.h \
		picenv.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) picenv.h -o moc_picenv.cpp

moc_playbk.cpp: playbk.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) playbk.h -o moc_playbk.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_clinetmainwindow.h ui_logindialog.h ui_registerdialog.h ui_networkconfigdialog.h ui_picenv.h ui_playbk.h
compiler_uic_clean:
	-$(DEL_FILE) ui_clinetmainwindow.h ui_logindialog.h ui_registerdialog.h ui_networkconfigdialog.h ui_picenv.h ui_playbk.h
ui_clinetmainwindow.h: clinetmainwindow.ui
	/usr/bin/uic-qt4 clinetmainwindow.ui -o ui_clinetmainwindow.h

ui_logindialog.h: logindialog.ui
	/usr/bin/uic-qt4 logindialog.ui -o ui_logindialog.h

ui_registerdialog.h: registerdialog.ui
	/usr/bin/uic-qt4 registerdialog.ui -o ui_registerdialog.h

ui_networkconfigdialog.h: networkconfigdialog.ui
	/usr/bin/uic-qt4 networkconfigdialog.ui -o ui_networkconfigdialog.h

ui_picenv.h: picenv.ui \
		qcustomplot.h
	/usr/bin/uic-qt4 picenv.ui -o ui_picenv.h

ui_playbk.h: playbk.ui
	/usr/bin/uic-qt4 playbk.ui -o ui_playbk.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp clinetmainwindow.h \
		picenv.h \
		qcustomplot.h \
		playbk.h \
		logindialog.h \
		registerdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

clinetmainwindow.o: clinetmainwindow.cpp clinetmainwindow.h \
		picenv.h \
		qcustomplot.h \
		playbk.h \
		ui_clinetmainwindow.h \
		clientsocket.h \
		CommandType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clinetmainwindow.o clinetmainwindow.cpp

clientsocket.o: clientsocket.cpp clientsocket.h \
		CommandType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientsocket.o clientsocket.cpp

logindialog.o: logindialog.cpp logindialog.h \
		ui_logindialog.h \
		registerdialog.h \
		networkconfigdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logindialog.o logindialog.cpp

registerdialog.o: registerdialog.cpp registerdialog.h \
		ui_registerdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registerdialog.o registerdialog.cpp

networkconfigdialog.o: networkconfigdialog.cpp networkconfigdialog.h \
		ui_networkconfigdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkconfigdialog.o networkconfigdialog.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

picenv.o: picenv.cpp picenv.h \
		qcustomplot.h \
		ui_picenv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picenv.o picenv.cpp

playbk.o: playbk.cpp playbk.h \
		ui_playbk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playbk.o playbk.cpp

moc_clinetmainwindow.o: moc_clinetmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clinetmainwindow.o moc_clinetmainwindow.cpp

moc_clientsocket.o: moc_clientsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientsocket.o moc_clientsocket.cpp

moc_logindialog.o: moc_logindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logindialog.o moc_logindialog.cpp

moc_registerdialog.o: moc_registerdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registerdialog.o moc_registerdialog.cpp

moc_networkconfigdialog.o: moc_networkconfigdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkconfigdialog.o moc_networkconfigdialog.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_picenv.o: moc_picenv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_picenv.o moc_picenv.cpp

moc_playbk.o: moc_playbk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playbk.o moc_playbk.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

